-- Enable Row Level Security
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- Users table (extends Supabase Auth)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  first_name text,
  last_name text,
  email text,
  phone text,
  address text,
  role_id bigint, -- Foreign key to roles table (defined below)
  property_scope text default 'Assigned', -- 'Global' or 'Assigned'
  tenant_id bigint, -- Link to tenants table
  owner_id bigint, -- Link to owners table
  status text default 'Active', -- 'Active', 'Suspended', 'Locked', 'Terminated'
  avatar_url text,
  avatar_asset_id uuid, -- Link to media_assets
  last_login timestamptz,
  mfa_enabled boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Roles table
create table public.roles (
  id bigint generated by default as identity primary key,
  name text unique not null,
  description text,
  is_locked boolean default false
);

-- Permissions table
create table public.permissions (
  id bigint generated by default as identity primary key,
  module text not null,
  action text not null,
  unique(module, action)
);

-- Role Permissions table
create table public.role_permissions (
  role_id bigint references public.roles(id) on delete cascade,
  permission_id bigint references public.permissions(id) on delete cascade,
  primary key (role_id, permission_id)
);

-- Permission Overrides table
create table public.permission_overrides (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  permission_id bigint references public.permissions(id) on delete cascade,
  override_type text not null, -- 'Grant', 'Deny'
  expiration_date timestamptz,
  created_at timestamptz default now()
);

-- Permission Requests table
create table public.permission_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  module text not null,
  action text not null,
  justification text,
  status text default 'Pending', -- 'Pending', 'Approved', 'Denied'
  reviewed_by uuid references public.profiles(id),
  expiration_date timestamptz,
  created_at timestamptz default now(),
  reviewed_at timestamptz
);

-- Owners table
create table public.owners (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text unique not null,
  phone text,
  address text,
  nationality text,
  dob date,
  id_type text,
  id_number text,
  id_expiry date,
  created_at timestamptz default now()
);

-- Properties table
create table public.properties (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null,
  type text not null,
  image_url text,
  image_asset_id uuid, -- Link to media_assets
  property_value numeric default 0,
  owner_id bigint references public.owners(id),
  status text default 'For Sale',
  amenities text default '[]',
  is_furnished boolean default false,
  description text,
  created_at timestamptz default now()
);

-- Units table
create table public.units (
  id bigint generated by default as identity primary key,
  property_id bigint references public.properties(id) on delete cascade,
  unit_number text not null,
  rent_amount numeric not null,
  status text default 'Vacant',
  created_at timestamptz default now()
);

-- Tenants table
create table public.tenants (
  id bigint generated by default as identity primary key,
  unit_id bigint references public.units(id),
  first_name text not null,
  last_name text not null,
  email text unique not null,
  phone text,
  lease_start date,
  lease_end date,
  notes text,
  auto_rent_reminders boolean default false,
  id_type text,
  id_number text,
  id_expiry_date date,
  nationality text,
  dob date,
  emergency_contact_name text,
  emergency_contact_phone text,
  emergency_contact_relation text,
  created_at timestamptz default now()
);

-- Tenant Documents table
create table public.tenant_documents (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete cascade,
  name text not null,
  url text not null,
  asset_id uuid, -- Link to media_assets
  type text not null,
  uploaded_at timestamptz default now()
);

-- Owner Documents table
create table public.owner_documents (
  id bigint generated by default as identity primary key,
  owner_id bigint references public.owners(id) on delete cascade,
  name text not null,
  url text not null,
  asset_id uuid, -- Link to media_assets
  type text not null,
  uploaded_at timestamptz default now()
);

-- Property Documents table
create table public.property_documents (
  id bigint generated by default as identity primary key,
  property_id bigint references public.properties(id) on delete cascade,
  name text not null,
  url text not null,
  asset_id uuid, -- Link to media_assets
  type text not null,
  uploaded_by uuid references public.profiles(id),
  uploaded_at timestamptz default now()
);

-- Maintenance Requests table
create table public.maintenance_requests (
  id bigint generated by default as identity primary key,
  unit_id bigint references public.units(id),
  tenant_id bigint references public.tenants(id),
  title text not null,
  description text,
  priority text default 'Medium',
  status text default 'Open',
  cost numeric default 0,
  time_spent numeric default 0,
  assigned_to uuid references public.profiles(id),
  created_at timestamptz default now()
);

-- Transactions table
create table public.transactions (
  id bigint generated by default as identity primary key,
  unit_id bigint references public.units(id),
  tenant_id bigint references public.tenants(id),
  amount numeric not null,
  type text not null, -- 'Rent', 'Late Fee', 'Maintenance', etc.
  status text default 'Pending',
  date timestamptz default now()
);

-- Property Images table
create table public.property_images (
  id bigint generated by default as identity primary key,
  property_id bigint references public.properties(id) on delete cascade,
  image_url text not null,
  asset_id uuid -- Link to media_assets
);

-- Media Assets table
create table public.media_assets (
  id uuid default gen_random_uuid() primary key,
  storage_path text not null,
  filename text not null,
  mime_type text,
  size bigint,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  uploaded_by uuid references public.profiles(id)
);

-- Messages table
create table public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references public.profiles(id), -- Assuming messages are between users now
  sender_type text not null, -- 'User', 'Tenant' (if tenants have user accounts)
  receiver_id uuid references public.profiles(id),
  receiver_type text not null,
  content text not null,
  timestamp timestamptz default now(),
  read boolean default false
);

-- Tasks table
create table public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  assignee text not null, -- Could be linked to users, but keeping as text for now
  due_date date not null,
  priority text default 'Medium',
  status text default 'Pending',
  cost numeric default 0,
  time_spent numeric default 0,
  created_at timestamptz default now()
);

-- Audit Logs table
create table public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  action text not null,
  timestamp timestamptz default now(),
  entity_type text,
  entity_id bigint
);

-- Role Hierarchy Rules table
create table public.role_hierarchy_rules (
  id bigint generated by default as identity primary key,
  type text not null, -- 'Inheritance' or 'Restricted'
  role_a_id bigint references public.roles(id),
  role_b_id bigint references public.roles(id),
  description text,
  created_at timestamptz default now()
);

-- User Property Access table
create table public.user_property_access (
  user_id uuid references public.profiles(id) on delete cascade,
  property_id bigint references public.properties(id) on delete cascade,
  primary key (user_id, property_id)
);

-- Add foreign key to profiles for roles
alter table public.profiles
  add constraint fk_profiles_roles foreign key (role_id) references public.roles(id);

alter table public.profiles
  add constraint fk_profiles_tenants foreign key (tenant_id) references public.tenants(id);

alter table public.profiles
  add constraint fk_profiles_owners foreign key (owner_id) references public.owners(id);

alter table public.profiles
  add constraint fk_profiles_media_assets foreign key (avatar_asset_id) references public.media_assets(id);

alter table public.properties
  add constraint fk_properties_media_assets foreign key (image_asset_id) references public.media_assets(id);

alter table public.tenant_documents
  add constraint fk_tenant_documents_media_assets foreign key (asset_id) references public.media_assets(id);

alter table public.owner_documents
  add constraint fk_owner_documents_media_assets foreign key (asset_id) references public.media_assets(id);

alter table public.property_images
  add constraint fk_property_images_media_assets foreign key (asset_id) references public.media_assets(id);


-- Enable RLS on all tables
alter table public.profiles enable row level security;
alter table public.roles enable row level security;
alter table public.permissions enable row level security;
alter table public.role_permissions enable row level security;
alter table public.permission_overrides enable row level security;
alter table public.permission_requests enable row level security;
alter table public.owners enable row level security;
alter table public.properties enable row level security;
alter table public.units enable row level security;
alter table public.tenants enable row level security;
alter table public.tenant_documents enable row level security;
alter table public.owner_documents enable row level security;
alter table public.maintenance_requests enable row level security;
alter table public.transactions enable row level security;
alter table public.property_images enable row level security;
alter table public.messages enable row level security;
alter table public.tasks enable row level security;
alter table public.audit_logs enable row level security;
alter table public.role_hierarchy_rules enable row level security;
alter table public.user_property_access enable row level security;
alter table public.media_assets enable row level security;
alter table public.property_documents enable row level security;

-- Helper function to check admin status (bypasses RLS to avoid recursion)
create or replace function public.is_admin()
returns boolean as $$
begin
  return exists (
    select 1 from public.profiles
    join public.roles on profiles.role_id = roles.id
    where profiles.id = auth.uid() and roles.name = 'System Administrator'
  );
end;
$$ language plpgsql security definer;

-- Create RLS Policies

-- Profiles: Users can read their own profile. Admins can read all.
drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile" on public.profiles
  for select using (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile" on public.profiles
  for insert with check (auth.uid() = id);

drop policy if exists "Admins have full access to profiles" on public.profiles;
create policy "Admins have full access to profiles" on public.profiles
  for all using (public.is_admin());

-- Roles: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read roles" on public.roles;
create policy "Authenticated users can read roles" on public.roles
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to roles" on public.roles;
create policy "Admins have full access to roles" on public.roles
  for all using (public.is_admin());

-- Permissions: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read permissions" on public.permissions;
create policy "Authenticated users can read permissions" on public.permissions
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to permissions" on public.permissions;
create policy "Admins have full access to permissions" on public.permissions
  for all using (public.is_admin());

-- Role Permissions: Admins can manage
drop policy if exists "Admins have full access to role_permissions" on public.role_permissions;
create policy "Admins have full access to role_permissions" on public.role_permissions
  for all using (public.is_admin());

-- Properties: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read properties" on public.properties;
create policy "Authenticated users can read properties" on public.properties
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to properties" on public.properties;
create policy "Admins have full access to properties" on public.properties
  for all using (public.is_admin());

-- Tenants: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read tenants" on public.tenants;
create policy "Authenticated users can read tenants" on public.tenants
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to tenants" on public.tenants;
create policy "Admins have full access to tenants" on public.tenants
  for all using (public.is_admin());

-- Owners: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read owners" on public.owners;
create policy "Authenticated users can read owners" on public.owners
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to owners" on public.owners;
create policy "Admins have full access to owners" on public.owners
  for all using (public.is_admin());

drop policy if exists "Owners can update their own record" on public.owners;
create policy "Owners can update their own record" on public.owners
  for update using (
    id in (
      select owner_id from public.profiles
      where profiles.id = auth.uid()
    )
  );

-- Units: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read units" on public.units;
create policy "Authenticated users can read units" on public.units
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to units" on public.units;
create policy "Admins have full access to units" on public.units
  for all using (public.is_admin());

-- Maintenance Requests: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read maintenance" on public.maintenance_requests;
create policy "Authenticated users can read maintenance" on public.maintenance_requests
  for select using (auth.role() = 'authenticated');

drop policy if exists "Authenticated users can insert maintenance" on public.maintenance_requests;
create policy "Authenticated users can insert maintenance" on public.maintenance_requests
  for insert with check (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to maintenance" on public.maintenance_requests;
create policy "Admins have full access to maintenance" on public.maintenance_requests
  for all using (public.is_admin());

-- Tasks: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read tasks" on public.tasks;
create policy "Authenticated users can read tasks" on public.tasks
  for select using (auth.role() = 'authenticated');

drop policy if exists "Authenticated users can insert tasks" on public.tasks;
create policy "Authenticated users can insert tasks" on public.tasks
  for insert with check (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to tasks" on public.tasks;
create policy "Admins have full access to tasks" on public.tasks
  for all using (public.is_admin());

-- Transactions: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read transactions" on public.transactions;
create policy "Authenticated users can read transactions" on public.transactions
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to transactions" on public.transactions;
create policy "Admins have full access to transactions" on public.transactions
  for all using (public.is_admin());

-- Messages: Users can read messages they are involved in. Admins can read all.
drop policy if exists "Users can read own messages" on public.messages;
create policy "Users can read own messages" on public.messages
  for select using (auth.uid() = sender_id or auth.uid() = receiver_id);

drop policy if exists "Users can insert messages" on public.messages;
create policy "Users can insert messages" on public.messages
  for insert with check (auth.uid() = sender_id);

drop policy if exists "Admins can read all messages" on public.messages;
create policy "Admins can read all messages" on public.messages
  for select using (public.is_admin());

-- Audit Logs: Readable by admins
drop policy if exists "Admins can read audit logs" on public.audit_logs;
create policy "Admins can read audit logs" on public.audit_logs
  for select using (public.is_admin());

drop policy if exists "Authenticated users can insert audit logs" on public.audit_logs;
create policy "Authenticated users can insert audit logs" on public.audit_logs
  for insert with check (auth.role() = 'authenticated');

-- Property Images: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read property images" on public.property_images;
create policy "Authenticated users can read property images" on public.property_images
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to property images" on public.property_images;
create policy "Admins have full access to property images" on public.property_images
  for all using (public.is_admin());

-- Documents: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read tenant docs" on public.tenant_documents;
create policy "Authenticated users can read tenant docs" on public.tenant_documents
  for select using (auth.role() = 'authenticated');

drop policy if exists "Authenticated users can read owner docs" on public.owner_documents;
create policy "Authenticated users can read owner docs" on public.owner_documents
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to tenant docs" on public.tenant_documents;
create policy "Admins have full access to tenant docs" on public.tenant_documents
  for all using (public.is_admin());

drop policy if exists "Admins have full access to owner docs" on public.owner_documents;
create policy "Admins have full access to owner docs" on public.owner_documents
  for all using (public.is_admin());

-- Property Documents Policies
drop policy if exists "Authenticated users can read property docs" on public.property_documents;
create policy "Authenticated users can read property docs" on public.property_documents
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to property docs" on public.property_documents;
create policy "Admins have full access to property docs" on public.property_documents
  for all using (public.is_admin());

-- Media Assets: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read media assets" on public.media_assets;
create policy "Authenticated users can read media assets" on public.media_assets
  for select using (auth.role() = 'authenticated');

drop policy if exists "Authenticated users can upload media assets" on public.media_assets;
create policy "Authenticated users can upload media assets" on public.media_assets
  for insert with check (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to media assets" on public.media_assets;
create policy "Admins have full access to media assets" on public.media_assets
  for all using (public.is_admin());

-- Create Storage Bucket
-- Note: This requires the storage schema to be enabled and permissions granted
insert into storage.buckets (id, name, public)
values ('hanti-assets', 'hanti-assets', true)
on conflict (id) do nothing;

-- Storage Policies
drop policy if exists "Public Access" on storage.objects;
create policy "Public Access" on storage.objects for select using (bucket_id = 'hanti-assets');

drop policy if exists "Authenticated Upload" on storage.objects;
create policy "Authenticated Upload" on storage.objects for insert with check (bucket_id = 'hanti-assets' and auth.role() = 'authenticated');

drop policy if exists "Authenticated Update" on storage.objects;
create policy "Authenticated Update" on storage.objects for update using (bucket_id = 'hanti-assets' and auth.role() = 'authenticated');

drop policy if exists "Authenticated Delete" on storage.objects;
create policy "Authenticated Delete" on storage.objects for delete using (bucket_id = 'hanti-assets' and auth.role() = 'authenticated');


-- Functions to handle new user creation
create or replace function public.handle_new_user()
returns trigger as $$
declare
  is_first_user boolean;
begin
  -- Check if this is the first user in the system
  select count(*) = 0 into is_first_user from public.profiles;
  
  insert into public.profiles (id, email, first_name, last_name, role_id)
  values (
    new.id, 
    new.email, 
    new.raw_user_meta_data->>'first_name', 
    new.raw_user_meta_data->>'last_name', 
    (select id from public.roles where name = (case when is_first_user then 'System Administrator' else 'Tenant' end) limit 1)
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new user creation
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Property Documents
create table public.property_documents (
  id bigint generated by default as identity primary key,
  property_id bigint references public.properties(id) on delete cascade not null,
  name text not null,
  url text not null,
  type text not null,
  asset_id text,
  uploaded_at timestamp with time zone default now(),
  uploaded_by uuid references auth.users(id)
);

alter table public.property_documents enable row level security;

create policy "Authenticated users can read property documents" on public.property_documents
  for select using (auth.role() = 'authenticated');

create policy "Admins can manage property documents" on public.property_documents
  for all using (public.is_admin());

-- Seed Data (Roles)
insert into public.roles (name, description, is_locked) values
('System Administrator', 'Full administrative control of the entire platform', true),
('Property Manager', 'Operational management of properties, units, and tenants', false),
('Leasing Agent', 'Handles tenant onboarding, leases, and unit availability', false),
('Maintenance Supervisor', 'Oversees maintenance requests and task assignments', false),
('Maintenance Technician', 'Executes assigned maintenance tasks and repairs', false),
('Accountant', 'Manages financial transactions, rent collection, and reporting', false),
('Property Owner', 'View-only access to their specific property portfolio', false),
('Tenant', 'Access to personal lease, payments, and maintenance requests', false),
('HR Manager', 'Manages internal staff users and roles', false),
('Security Officer', 'Monitors audit logs and security alerts', false);

-- Seed Permissions (Full set)
insert into public.permissions (module, action) values
('PROPERTY_MANAGEMENT', 'view'),
('PROPERTY_MANAGEMENT', 'create'),
('PROPERTY_MANAGEMENT', 'update'),
('PROPERTY_MANAGEMENT', 'delete'),
('TENANT_MANAGEMENT', 'view'),
('TENANT_MANAGEMENT', 'create'),
('TENANT_MANAGEMENT', 'update'),
('TENANT_MANAGEMENT', 'delete'),
('USER_MANAGEMENT', 'view'),
('USER_MANAGEMENT', 'create'),
('USER_MANAGEMENT', 'update'),
('USER_MANAGEMENT', 'delete'),
('ADMIN_GOVERNANCE', 'view'),
('ADMIN_GOVERNANCE', 'manage'),
('PERMISSION_MANAGEMENT', 'view'),
('PERMISSION_MANAGEMENT', 'manage'),
('FINANCE', 'view'),
('FINANCE', 'manage'),
('MAINTENANCE', 'view'),
('MAINTENANCE', 'manage'),
('MAINTENANCE', 'assign'),
('MAINTENANCE', 'close');

-- Grant permissions to Admin
insert into public.role_permissions (role_id, permission_id)
select (select id from public.roles where name = 'System Administrator'), id from public.permissions;

