-- Enable Row Level Security
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- Users table (extends Supabase Auth)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  first_name text,
  last_name text,
  email text,
  phone text,
  address text,
  role_id bigint, -- Foreign key to roles table (defined below)
  property_scope text default 'Assigned', -- 'Global' or 'Assigned'
  tenant_id bigint, -- Link to tenants table
  owner_id bigint, -- Link to owners table
  vendor_id bigint, -- Link to vendors table
  status text default 'Active', -- 'Active', 'Suspended', 'Locked', 'Terminated'
  avatar_url text,
  avatar_asset_id uuid, -- Link to media_assets
  last_login timestamptz,
  mfa_enabled boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Roles table
create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text unique not null,
  description text,
  is_locked boolean default false
);

-- Permissions table
create table if not exists public.permissions (
  id bigint generated by default as identity primary key,
  module text not null,
  action text not null,
  unique(module, action)
);

-- Role Permissions table
create table if not exists public.role_permissions (
  role_id bigint references public.roles(id) on delete cascade,
  permission_id bigint references public.permissions(id) on delete cascade,
  primary key (role_id, permission_id)
);

-- Permission Overrides table
create table if not exists public.permission_overrides (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  permission_id bigint references public.permissions(id) on delete cascade,
  override_type text not null, -- 'Grant', 'Deny'
  expiration_date timestamptz,
  created_at timestamptz default now()
);

-- Permission Requests table
create table if not exists public.permission_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  module text not null,
  action text not null,
  justification text,
  status text default 'Pending', -- 'Pending', 'Approved', 'Denied'
  reviewed_by uuid references public.profiles(id),
  expiration_date timestamptz,
  created_at timestamptz default now(),
  reviewed_at timestamptz
);

-- Owners table
create table if not exists public.owners (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text unique not null,
  phone text,
  address text,
  nationality text,
  dob date,
  id_type text,
  id_number text,
  id_expiry date,
  created_at timestamptz default now()
);

-- Properties table
create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null,
  type text not null,
  image_url text,
  image_asset_id uuid, -- Link to media_assets
  property_value numeric default 0,
  owner_id bigint references public.owners(id),
  status text default 'For Sale',
  amenities text default '[]',
  is_furnished boolean default false,
  description text,
  available_from date,
  created_at timestamptz default now()
);

-- Ensure properties table has available_from if it was created without it
DO $$ 
BEGIN 
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'properties' AND column_name = 'available_from') THEN
    ALTER TABLE public.properties ADD COLUMN available_from date;
  END IF;
END $$;

-- Units table
create table if not exists public.units (
  id bigint generated by default as identity primary key,
  property_id bigint references public.properties(id) on delete cascade,
  unit_number text not null,
  rent_amount numeric not null,
  status text default 'Vacant',
  created_at timestamptz default now()
);

-- Tenants table
create table if not exists public.tenants (
  id bigint generated by default as identity primary key,
  unit_id bigint references public.units(id),
  first_name text not null,
  last_name text not null,
  email text unique not null,
  phone text,
  lease_start date,
  lease_end date,
  notes text,
  auto_rent_reminders boolean default false,
  id_type text,
  id_number text,
  id_expiry_date date,
  nationality text,
  dob date,
  emergency_contact_name text,
  emergency_contact_phone text,
  emergency_contact_relation text,
  status text default 'Prospective', -- 'Prospective', 'Active', 'Evicted', 'Terminated', 'Archived'
  tenant_id_number text,
  occupation text,
  employer text,
  monthly_income numeric default 0,
  occupants_count integer default 1,
  occupant_details text,
  preferred_language text default 'Somali',
  vehicle_info text,
  rental_history text,
  guarantor_details text,
  current_balance numeric default 0,
  security_deposit_held numeric default 0,
  created_at timestamptz default now()
);

-- Tenant Documents table
create table if not exists public.tenant_documents (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete cascade,
  name text not null,
  url text not null,
  asset_id uuid, -- Link to media_assets
  type text not null,
  uploaded_at timestamptz default now()
);

-- Owner Documents table
create table if not exists public.owner_documents (
  id bigint generated by default as identity primary key,
  owner_id bigint references public.owners(id) on delete cascade,
  name text not null,
  url text not null,
  asset_id uuid, -- Link to media_assets
  type text not null,
  uploaded_at timestamptz default now()
);

-- Maintenance Requests table
create table if not exists public.maintenance_requests (
  id bigint generated by default as identity primary key,
  unit_id bigint references public.units(id),
  tenant_id bigint references public.tenants(id),
  title text not null,
  description text,
  priority text default 'Medium',
  status text default 'Open',
  cost numeric default 0,
  time_spent numeric default 0,
  assigned_to uuid references public.profiles(id),
  created_at timestamptz default now()
);

-- Property Images table
create table if not exists public.property_images (
  id bigint generated by default as identity primary key,
  property_id bigint references public.properties(id) on delete cascade,
  image_url text not null,
  asset_id uuid -- Link to media_assets
);

-- Media Assets table
create table if not exists public.media_assets (
  id uuid default gen_random_uuid() primary key,
  storage_path text not null,
  filename text not null,
  mime_type text,
  size bigint,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  uploaded_by uuid references public.profiles(id)
);

-- Messages table
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references public.profiles(id), -- Assuming messages are between users now
  sender_type text not null, -- 'User', 'Tenant' (if tenants have user accounts)
  receiver_id uuid references public.profiles(id),
  receiver_type text not null,
  content text not null,
  timestamp timestamptz default now(),
  read boolean default false
);

-- Tasks table
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  assignee text not null, -- Could be linked to users, but keeping as text for now
  due_date date not null,
  priority text default 'Medium',
  status text default 'Pending',
  cost numeric default 0,
  time_spent numeric default 0,
  property_id bigint references public.properties(id) on delete cascade,
  unit_id bigint references public.units(id) on delete set null,
  created_at timestamptz default now()
);

-- Audit Logs table
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  action text not null,
  timestamp timestamptz default now(),
  entity_type text,
  entity_id bigint
);

-- Role Hierarchy Rules table
create table if not exists public.role_hierarchy_rules (
  id bigint generated by default as identity primary key,
  type text not null, -- 'Inheritance' or 'Restricted'
  role_a_id bigint references public.roles(id),
  role_b_id bigint references public.roles(id),
  description text,
  created_at timestamptz default now()
);

-- User Property Access table
create table if not exists public.user_property_access (
  user_id uuid references public.profiles(id) on delete cascade,
  property_id bigint references public.properties(id) on delete cascade,
  primary key (user_id, property_id)
);

-- Add foreign key to profiles for roles (with check to prevent error if already exists)
DO $$ 
BEGIN 
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'vendor_id') THEN
    ALTER TABLE public.profiles ADD COLUMN vendor_id bigint;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_profiles_roles') THEN
    alter table public.profiles add constraint fk_profiles_roles foreign key (role_id) references public.roles(id);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_profiles_tenants') THEN
    alter table public.profiles add constraint fk_profiles_tenants foreign key (tenant_id) references public.tenants(id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_profiles_owners') THEN
    alter table public.profiles add constraint fk_profiles_owners foreign key (owner_id) references public.owners(id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_profiles_vendors') THEN
    alter table public.profiles add constraint fk_profiles_vendors foreign key (vendor_id) references public.vendors(id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_profiles_media_assets') THEN
    alter table public.profiles add constraint fk_profiles_media_assets foreign key (avatar_asset_id) references public.media_assets(id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_properties_media_assets') THEN
    alter table public.properties add constraint fk_properties_media_assets foreign key (image_asset_id) references public.media_assets(id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tenant_documents_media_assets') THEN
    alter table public.tenant_documents add constraint fk_tenant_documents_media_assets foreign key (asset_id) references public.media_assets(id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_owner_documents_media_assets') THEN
    alter table public.owner_documents add constraint fk_owner_documents_media_assets foreign key (asset_id) references public.media_assets(id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_property_images_media_assets') THEN
    alter table public.property_images add constraint fk_property_images_media_assets foreign key (asset_id) references public.media_assets(id);
  END IF;

  -- Ensure tenants table has financial columns
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'tenants' AND column_name = 'current_balance') THEN
    ALTER TABLE public.tenants ADD COLUMN current_balance numeric DEFAULT 0;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'tenants' AND column_name = 'security_deposit_held') THEN
    ALTER TABLE public.tenants ADD COLUMN security_deposit_held numeric DEFAULT 0;
  END IF;

  -- Ensure tasks table has property_id and unit_id
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'tasks' AND column_name = 'property_id') THEN
    ALTER TABLE public.tasks ADD COLUMN property_id bigint REFERENCES public.properties(id) ON DELETE CASCADE;
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'tasks' AND column_name = 'unit_id') THEN
    ALTER TABLE public.tasks ADD COLUMN unit_id bigint REFERENCES public.units(id) ON DELETE SET NULL;
  END IF;

  -- Ensure units table has the new room metrics
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'units' AND column_name = 'living_rooms') THEN
    ALTER TABLE public.units ADD COLUMN living_rooms integer DEFAULT 0;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'units' AND column_name = 'bedrooms') THEN
    ALTER TABLE public.units ADD COLUMN bedrooms integer DEFAULT 0;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'units' AND column_name = 'bathrooms') THEN
    ALTER TABLE public.units ADD COLUMN bathrooms integer DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'messages' AND column_name = 'attachment_url') THEN
    ALTER TABLE public.messages ADD COLUMN attachment_url text;
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'messages' AND column_name = 'attachment_name') THEN
    ALTER TABLE public.messages ADD COLUMN attachment_name text;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'tenants' AND column_name = 'user_id') THEN
    ALTER TABLE public.tenants ADD COLUMN user_id uuid references public.profiles(id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'owners' AND column_name = 'user_id') THEN
    ALTER TABLE public.owners ADD COLUMN user_id uuid references public.profiles(id);
  END IF;
END $$;

-- ---------------------------------------------------------
-- INDUSTRY STANDARD ENHANCEMENTS (Financials & Operations)
-- ---------------------------------------------------------

-- 1. Vendors Table (Standardizing Contractor Management)
create table if not exists public.vendors (
  id bigint generated always as identity primary key,
  company_name text not null,
  contact_person text,
  email text,
  phone text,
  category text, -- Plumber, Electrician, etc.
  status text default 'Active', -- Active, Inactive, Blacklisted
  tax_id text,
  address text,
  insurance_url text,
  insurance_expiry date,
  certification_url text,
  rating decimal(3,2) default 5.0,
  created_at timestamptz default now()
);

-- 2. Transactions Table (Double-Entry Ledger Foundation)
-- This section unifies the previous definitions and ensures all columns exist
create table if not exists public.transactions (
  id bigint generated always as identity primary key,
  tenant_id bigint references public.tenants(id) on delete set null,
  property_id bigint references public.properties(id) on delete set null,
  unit_id bigint references public.units(id) on delete set null,
  amount decimal(12,2) not null,
  type text not null, -- 'Charge', 'Payment', 'Refund', 'Adjustment'
  category text not null, -- 'Rent', 'Security Deposit', 'Utilities', 'Late Fee'
  status text default 'Completed', -- 'Pending', 'Completed', 'Failed', 'Void'
  description text,
  transaction_date date default current_date,
  metadata jsonb default '{}', -- For payment gateway IDs, etc.
  created_at timestamptz default now()
);

-- Migration for existing transactions table
DO $$ 
BEGIN 
  -- Ensure property_id exists
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'transactions' AND column_name = 'property_id') THEN
    ALTER TABLE public.transactions ADD COLUMN property_id bigint REFERENCES public.properties(id) ON DELETE SET NULL;
  END IF;

  -- Ensure category exists (replaces type in some contexts or complements it)
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'transactions' AND column_name = 'category') THEN
    ALTER TABLE public.transactions ADD COLUMN category text DEFAULT 'Rent';
  END IF;

  -- Ensure transaction_date exists
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'transactions' AND column_name = 'transaction_date') THEN
    ALTER TABLE public.transactions ADD COLUMN transaction_date date DEFAULT current_date;
  END IF;

  -- Ensure created_at exists
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'transactions' AND column_name = 'created_at') THEN
    ALTER TABLE public.transactions ADD COLUMN created_at timestamptz DEFAULT now();
  END IF;

  -- Ensure unit_id exists
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'transactions' AND column_name = 'unit_id') THEN
    ALTER TABLE public.transactions ADD COLUMN unit_id bigint REFERENCES public.units(id) ON DELETE SET NULL;
  END IF;
END $$;

-- 3. Maintenance Work Orders (Professional Vendor flow)
create table if not exists public.work_orders (
  id bigint generated always as identity primary key,
  request_id bigint references public.maintenance_requests(id) on delete cascade,
  vendor_id bigint references public.vendors(id) on delete set null,
  status text default 'Draft', -- Draft, Issued, In Progress, Completed, Paid
  estimated_cost decimal(10,2),
  actual_cost decimal(10,2),
  scheduled_date date,
  completion_date date,
  instructions text,
  created_at timestamptz default now()
);

-- 4. Rent Generation Logs (For Automated Rent Engine)
create table if not exists public.rent_generation_logs (
  id bigint generated always as identity primary key,
  month integer not null,
  year integer not null,
  generated_at timestamptz default now(),
  status text default 'Success',
  total_charges integer default 0,
  total_amount decimal(12,2) default 0,
  unique(month, year)
);

-- Trigger to update tenant balance on transaction
create or replace function public.update_tenant_balance()
returns trigger as $$
begin
  if new.tenant_id is not null then
    if new.type = 'Charge' then
      update public.tenants 
      set current_balance = current_balance + new.amount 
      where id = new.tenant_id;
    elsif new.type = 'Payment' then
      update public.tenants 
      set current_balance = current_balance - new.amount 
      where id = new.tenant_id;
    elsif new.type = 'Refund' then
      update public.tenants 
      set current_balance = current_balance + new.amount 
      where id = new.tenant_id;
    end if;

    -- Special handling for Security Deposits
    if new.category = 'Security Deposit' then
       if new.type = 'Payment' then
         update public.tenants set security_deposit_held = security_deposit_held + new.amount where id = new.tenant_id;
       elsif new.type = 'Refund' then
         update public.tenants set security_deposit_held = security_deposit_held - new.amount where id = new.tenant_id;
       end if;
    end if;
  end if;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_transaction_inserted on public.transactions;
create trigger on_transaction_inserted
  after insert on public.transactions
  for each row execute procedure public.update_tenant_balance();

-- Migration for maintenance_requests to include vendor_id
DO $$ 
BEGIN 
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'maintenance_requests' AND column_name = 'vendor_id') THEN
    ALTER TABLE public.maintenance_requests ADD COLUMN vendor_id bigint REFERENCES public.vendors(id) ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'vendors' AND column_name = 'insurance_expiry') THEN
    ALTER TABLE public.vendors ADD COLUMN insurance_expiry date;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'vendors' AND column_name = 'certification_url') THEN
    ALTER TABLE public.vendors ADD COLUMN certification_url text;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'vendors' AND column_name = 'insurance_url') THEN
    ALTER TABLE public.vendors ADD COLUMN insurance_url text;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'vendors' AND column_name = 'rating') THEN
    ALTER TABLE public.vendors ADD COLUMN rating decimal(3,2) default 5.0;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'vendors' AND column_name = 'address') THEN
    ALTER TABLE public.vendors ADD COLUMN address text;
  END IF;
END $$;

create table if not exists public.vendor_reviews (
  id bigint generated always as identity primary key,
  vendor_id bigint references public.vendors(id) on delete cascade,
  user_id uuid references public.profiles(id),
  rating integer,
  review_text text,
  created_at timestamptz default now()
);

-- Enable RLS for new tables
alter table public.vendors enable row level security;
alter table public.vendor_reviews enable row level security;
alter table public.work_orders enable row level security;
alter table public.rent_generation_logs enable row level security;

-- Policies for Vendors
drop policy if exists "Authenticated users can read vendors" on public.vendors;
create policy "Authenticated users can read vendors" on public.vendors
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins and Managers can manage vendors" on public.vendors;
create policy "Admins and Managers can manage vendors" on public.vendors
  for all using (public.is_admin());

-- Policies for Vendor Reviews
drop policy if exists "Authenticated users can read vendor reviews" on public.vendor_reviews;
create policy "Authenticated users can read vendor reviews" on public.vendor_reviews
  for select using (auth.role() = 'authenticated');

drop policy if exists "Authenticated users can manage vendor reviews" on public.vendor_reviews;
create policy "Authenticated users can manage vendor reviews" on public.vendor_reviews
  for all using (auth.role() = 'authenticated');

-- Policies for Work Orders
drop policy if exists "Authenticated users can read work orders" on public.work_orders;
create policy "Authenticated users can read work orders" on public.work_orders
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins and Managers can manage work orders" on public.work_orders;
create policy "Admins and Managers can manage work orders" on public.work_orders
  for all using (public.is_admin());

-- Policies for Rent Generation Logs
drop policy if exists "Admins can read rent logs" on public.rent_generation_logs;
create policy "Admins can read rent logs" on public.rent_generation_logs
  for select using (public.is_admin());

-- Transaction Security (Granular)
drop policy if exists "Tenants can view own transactions" on public.transactions;
create policy "Tenants can view own transactions" on public.transactions
  for select using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.tenant_id = transactions.tenant_id
    )
  );

drop policy if exists "Owners can view their property transactions" on public.transactions;
create policy "Owners can view their property transactions" on public.transactions
  for select using (
    exists (
      select 1 from public.profiles
      join public.properties on profiles.owner_id = properties.owner_id
      where profiles.id = auth.uid() and properties.id = transactions.property_id
    )
  );

-- Work Order Vendor Privacy
drop policy if exists "Vendors can view assigned work orders" on public.work_orders;
create policy "Vendors can view assigned work orders" on public.work_orders
  for select using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.vendor_id = work_orders.vendor_id
    )
  );

drop policy if exists "Vendors can update assigned work orders" on public.work_orders;
create policy "Vendors can update assigned work orders" on public.work_orders
  for update using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.vendor_id = work_orders.vendor_id
    )
  );


-- Enable RLS on all tables
alter table public.profiles enable row level security;
alter table public.roles enable row level security;
alter table public.permissions enable row level security;
alter table public.role_permissions enable row level security;
alter table public.permission_overrides enable row level security;
alter table public.permission_requests enable row level security;
alter table public.owners enable row level security;
alter table public.properties enable row level security;
alter table public.units enable row level security;
alter table public.tenants enable row level security;
alter table public.tenant_documents enable row level security;
alter table public.owner_documents enable row level security;
alter table public.maintenance_requests enable row level security;
alter table public.transactions enable row level security;
alter table public.property_images enable row level security;
alter table public.messages enable row level security;
alter table public.tasks enable row level security;
alter table public.audit_logs enable row level security;
alter table public.role_hierarchy_rules enable row level security;
alter table public.user_property_access enable row level security;
alter table public.media_assets enable row level security;

-- Helper function to check admin status (bypasses RLS to avoid recursion)
create or replace function public.is_admin()
returns boolean as $$
begin
  return exists (
    select 1 from public.profiles
    join public.roles on profiles.role_id = roles.id
    where profiles.id = auth.uid() and roles.name in ('System Administrator', 'HR Manager', 'Property Manager', 'Finance Team')
  );
end;
$$ language plpgsql security definer;

-- Create RLS Policies

-- Profiles: Users can read their own profile. Admins can read all.
drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile" on public.profiles
  for select using (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile" on public.profiles
  for insert with check (auth.uid() = id);

drop policy if exists "Admins have full access to profiles" on public.profiles;
create policy "Admins have full access to profiles" on public.profiles
  for all using (public.is_admin() or auth.uid() = id);

-- Roles: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read roles" on public.roles;
create policy "Authenticated users can read roles" on public.roles
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to roles" on public.roles;
create policy "Admins have full access to roles" on public.roles
  for all using (public.is_admin());

-- Permissions: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read permissions" on public.permissions;
create policy "Authenticated users can read permissions" on public.permissions
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to permissions" on public.permissions;
create policy "Admins have full access to permissions" on public.permissions
  for all using (public.is_admin());

-- Role Permissions: Admins can manage
drop policy if exists "Admins have full access to role_permissions" on public.role_permissions;
create policy "Admins have full access to role_permissions" on public.role_permissions
  for all using (public.is_admin());

-- Properties: Readable by authenticated users. Admins and managers can manage.
drop policy if exists "Authenticated users can read properties" on public.properties;
create policy "Authenticated users can read properties" on public.properties
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins and Managers can manage properties" on public.properties;
create policy "Admins and Managers can manage properties" on public.properties
  for all using (
    public.is_admin() or 
    exists (
      select 1 from public.profiles prof
      join public.roles r on prof.role_id = r.id
      where prof.id = auth.uid() and r.name in ('Property Manager', 'Leasing Agent', 'Maintenance Supervisor')
    )
  );

-- Tenants: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read tenants" on public.tenants;
create policy "Authenticated users can read tenants" on public.tenants
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to tenants" on public.tenants;
create policy "Admins have full access to tenants" on public.tenants
  for all using (public.is_admin());

-- Owners: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read owners" on public.owners;
create policy "Authenticated users can read owners" on public.owners
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to owners" on public.owners;
create policy "Admins have full access to owners" on public.owners
  for all using (public.is_admin());

drop policy if exists "Owners can update their own record" on public.owners;
create policy "Owners can update their own record" on public.owners
  for update using (
    id in (
      select owner_id from public.profiles
      where profiles.id = auth.uid()
    )
  );

-- Units: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read units" on public.units;
create policy "Authenticated users can read units" on public.units
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to units" on public.units;
create policy "Admins have full access to units" on public.units
  for all using (public.is_admin());

-- Maintenance Requests: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read maintenance" on public.maintenance_requests;
create policy "Authenticated users can read maintenance" on public.maintenance_requests
  for select using (auth.role() = 'authenticated');

drop policy if exists "Authenticated users can insert maintenance" on public.maintenance_requests;
create policy "Authenticated users can insert maintenance" on public.maintenance_requests
  for insert with check (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to maintenance" on public.maintenance_requests;
create policy "Admins have full access to maintenance" on public.maintenance_requests
  for all using (public.is_admin());

-- Tasks: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read tasks" on public.tasks;
create policy "Authenticated users can read tasks" on public.tasks
  for select using (auth.role() = 'authenticated');

drop policy if exists "Authenticated users can insert tasks" on public.tasks;
create policy "Authenticated users can insert tasks" on public.tasks
  for insert with check (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to tasks" on public.tasks;
create policy "Admins have full access to tasks" on public.tasks
  for all using (public.is_admin());

-- Transactions: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read transactions" on public.transactions;
create policy "Authenticated users can read transactions" on public.transactions
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to transactions" on public.transactions;
create policy "Admins have full access to transactions" on public.transactions
  for all using (public.is_admin());

-- Messages: Users can read messages they are involved in. Admins can read all.
drop policy if exists "Users can read own messages" on public.messages;
create policy "Users can read own messages" on public.messages
  for select using (auth.uid() = sender_id or auth.uid() = receiver_id);

drop policy if exists "Users can insert messages" on public.messages;
create policy "Users can insert messages" on public.messages
  for insert with check (auth.uid() = sender_id);

drop policy if exists "Admins can read all messages" on public.messages;
create policy "Admins can read all messages" on public.messages
  for select using (public.is_admin());

-- Audit Logs: Readable by admins
drop policy if exists "Admins can read audit logs" on public.audit_logs;
create policy "Admins can read audit logs" on public.audit_logs
  for select using (public.is_admin());

drop policy if exists "Authenticated users can insert audit logs" on public.audit_logs;
create policy "Authenticated users can insert audit logs" on public.audit_logs
  for insert with check (auth.role() = 'authenticated');

-- Property Images: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read property images" on public.property_images;
create policy "Authenticated users can read property images" on public.property_images
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to property images" on public.property_images;
create policy "Admins have full access to property images" on public.property_images
  for all using (public.is_admin());

-- Documents: Readable by authenticated users. Admins can manage.
drop policy if exists "Authenticated users can read tenant docs" on public.tenant_documents;
create policy "Authenticated users can read tenant docs" on public.tenant_documents
  for select using (auth.role() = 'authenticated');

drop policy if exists "Authenticated users can read owner docs" on public.owner_documents;
create policy "Authenticated users can read owner docs" on public.owner_documents
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to tenant docs" on public.tenant_documents;
create policy "Admins have full access to tenant docs" on public.tenant_documents
  for all using (public.is_admin());

drop policy if exists "Admins have full access to owner docs" on public.owner_documents;
create policy "Admins have full access to owner docs" on public.owner_documents
  for all using (public.is_admin());

-- Property Documents Policies
drop table if exists public.property_documents cascade;
create table public.property_documents (
  id bigint generated by default as identity primary key,
  property_id bigint references public.properties(id) on delete cascade not null,
  name text not null,
  url text not null,
  type text not null,
  asset_id uuid references public.media_assets(id),
  uploaded_at timestamp with time zone default now(),
  uploaded_by uuid references public.profiles(id)
);

-- Document Templates
drop table if exists public.document_templates cascade;
create table public.document_templates (
  id bigint generated by default as identity primary key,
  category text not null, -- 'Lease', 'Notice', 'Financial', 'Property Management'
  name_en text not null,
  name_so text not null,
  content_en text not null,
  content_so text not null,
  placeholders jsonb default '[]'::jsonb,
  is_active boolean default true,
  created_at timestamptz default now()
);

-- Legal Documents (Generated from templates)
drop table if exists public.legal_documents cascade;
create table public.legal_documents (
  id bigint generated by default as identity primary key,
  template_id bigint references public.document_templates(id) on delete set null,
  property_id bigint references public.properties(id) on delete cascade,
  unit_id bigint references public.units(id) on delete cascade,
  tenant_id bigint references public.tenants(id) on delete cascade,
  owner_id bigint references public.owners(id) on delete cascade,
  title text not null,
  content_en text not null,
  content_so text not null,
  placeholders_data jsonb default '{}'::jsonb,
  status text default 'Draft', -- 'Draft', 'Pending', 'Signed', 'Expired', 'Archived'
  version integer default 1,
  file_url text,
  asset_id uuid references public.media_assets(id),
  created_by uuid references public.profiles(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Document Signatures
drop table if exists public.document_signatures cascade;
create table public.document_signatures (
  id bigint generated by default as identity primary key,
  document_id bigint references public.legal_documents(id) on delete cascade,
  signer_id uuid references public.profiles(id),
  signer_name text,
  signer_role text, -- 'Landlord', 'Tenant', 'Witness'
  signature_data text, 
  signed_at timestamptz,
  ip_address text,
  user_agent text
);

alter table public.property_documents enable row level security;
alter table public.document_templates enable row level security;
alter table public.legal_documents enable row level security;
alter table public.document_signatures enable row level security;

-- Policies for property_documents
drop policy if exists "Authenticated users can read property docs" on public.property_documents;
create policy "Authenticated users can read property docs" on public.property_documents
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins and Managers can manage property docs" on public.property_documents;
create policy "Admins and Managers can manage property docs" on public.property_documents
  for all using (
    public.is_admin() or 
    exists (
      select 1 from public.profiles prof
      join public.roles r on prof.role_id = r.id
      where prof.id = auth.uid() and r.name in ('Property Manager', 'Leasing Agent')
    )
  );

-- Policies for Document Templates
drop policy if exists "Authenticated users can view templates" on public.document_templates;
create policy "Authenticated users can view templates" on public.document_templates
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins can manage templates" on public.document_templates;
create policy "Admins can manage templates" on public.document_templates
  for all using (public.is_admin());

-- Policies for Legal Documents
drop policy if exists "Authenticated users can view legal docs" on public.legal_documents;
create policy "Authenticated users can view legal docs" on public.legal_documents
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins and Managers can manage legal docs" on public.legal_documents;
create policy "Admins and Managers can manage legal docs" on public.legal_documents
  for all using (
    public.is_admin() or 
    exists (
      select 1 from public.profiles prof
      join public.roles r on prof.role_id = r.id
      where prof.id = auth.uid() and r.name in ('Property Manager', 'Leasing Agent')
    )
  );

-- Policies for Signatures
drop policy if exists "Authenticated users can view signatures" on public.document_signatures;
create policy "Authenticated users can view signatures" on public.document_signatures
  for select using (auth.role() = 'authenticated');

drop policy if exists "Authenticated users can sign docs" on public.document_signatures;
create policy "Authenticated users can sign docs" on public.document_signatures
  for insert with check (auth.role() = 'authenticated');

drop policy if exists "Public Access" on storage.objects;
create policy "Public Access" on storage.objects for select using (bucket_id = 'hanti-assets');

drop policy if exists "Authenticated Upload" on storage.objects;
create policy "Authenticated Upload" on storage.objects for insert with check (bucket_id = 'hanti-assets' and auth.role() = 'authenticated');

drop policy if exists "Authenticated Update" on storage.objects;
create policy "Authenticated Update" on storage.objects for update using (bucket_id = 'hanti-assets' and auth.role() = 'authenticated');

drop policy if exists "Authenticated Delete" on storage.objects;
create policy "Authenticated Delete" on storage.objects for delete using (bucket_id = 'hanti-assets' and auth.role() = 'authenticated');


-- Functions to handle new user creation
create or replace function public.handle_new_user()
returns trigger as $$
declare
  is_first_user boolean;
  target_role_name text;
begin
  -- Check if this is the first user in the system
  select count(*) = 0 into is_first_user from public.profiles;
  
  if is_first_user or new.email = 'sleqcsleqc@gmail.com' then
    target_role_name := 'System Administrator';
  else
    target_role_name := 'Tenant';
  end if;

  insert into public.profiles (id, email, first_name, last_name, role_id)
  values (
    new.id, 
    new.email, 
    new.raw_user_meta_data->>'first_name', 
    new.raw_user_meta_data->>'last_name', 
    (select id from public.roles where name = target_role_name limit 1)
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new user creation
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Seed Data (Roles) - Use ON CONFLICT to prevent duplicates
insert into public.roles (name, description, is_locked) values
('System Administrator', 'Full administrative control of the entire platform', true),
('Property Manager', 'Operational management of properties, units, and tenants', false),
('Leasing Agent', 'Handles tenant onboarding, leases, and unit availability', false),
('Maintenance Supervisor', 'Oversees maintenance requests and task assignments', false),
('Maintenance Technician', 'Executes assigned maintenance tasks and repairs', false),
('Accountant', 'Manages financial transactions, rent collection, and reporting', false),
('Property Owner', 'View-only access to their specific property portfolio', false),
('Tenant', 'Access to personal lease, payments, and maintenance requests', false),
('HR Manager', 'Manages internal staff users and roles', false),
('Security Officer', 'Monitors audit logs and security alerts', false)
ON CONFLICT (name) DO NOTHING;

-- Seed Permissions (Full set)
insert into public.permissions (module, action) values
('PROPERTY_MANAGEMENT', 'view'),
('PROPERTY_MANAGEMENT', 'create'),
('PROPERTY_MANAGEMENT', 'update'),
('PROPERTY_MANAGEMENT', 'delete'),
('TENANT_MANAGEMENT', 'view'),
('TENANT_MANAGEMENT', 'create'),
('TENANT_MANAGEMENT', 'update'),
('TENANT_MANAGEMENT', 'delete'),
('USER_MANAGEMENT', 'view'),
('USER_MANAGEMENT', 'create'),
('USER_MANAGEMENT', 'update'),
('USER_MANAGEMENT', 'delete'),
('ADMIN_GOVERNANCE', 'view'),
('ADMIN_GOVERNANCE', 'manage'),
('PERMISSION_MANAGEMENT', 'view'),
('PERMISSION_MANAGEMENT', 'manage'),
('FINANCE', 'view'),
('FINANCE', 'manage'),
('MAINTENANCE', 'view'),
('MAINTENANCE', 'manage'),
('MAINTENANCE', 'assign'),
('MAINTENANCE', 'close')
ON CONFLICT (module, action) DO NOTHING;

-- Grant permissions to Admin
insert into public.role_permissions (role_id, permission_id)
select (select id from public.roles where name = 'System Administrator'), id from public.permissions
ON CONFLICT DO NOTHING;

-- Grant permissions to Property Manager
insert into public.role_permissions (role_id, permission_id)
select (select id from public.roles where name = 'Property Manager'), id 
from public.permissions 
where module in ('PROPERTY_MANAGEMENT', 'TENANT_MANAGEMENT', 'MAINTENANCE', 'FINANCE')
ON CONFLICT DO NOTHING;

-- Grant permissions to Leasing Agent
insert into public.role_permissions (role_id, permission_id)
select (select id from public.roles where name = 'Leasing Agent'), id 
from public.permissions 
where module in ('PROPERTY_MANAGEMENT', 'TENANT_MANAGEMENT')
ON CONFLICT DO NOTHING;

-- Promote the user to System Administrator for development
update public.profiles 
set role_id = (select id from public.roles where name = 'System Administrator'),
    property_scope = 'Global'
where email in ('sleqcsleqc@gmail.com', 'admin@hantimaster.com');

-- 20. Leasing Applications Table

CREATE TABLE IF NOT EXISTS public.leasing_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT REFERENCES public.properties(id) ON DELETE CASCADE,
    unit_id BIGINT REFERENCES public.units(id) ON DELETE SET NULL,
    applicant_name VARCHAR(255) NOT NULL,
    applicant_email VARCHAR(255) NOT NULL,
    applicant_phone VARCHAR(50),
    status VARCHAR(50) DEFAULT 'Pending' CHECK (status IN ('Pending', 'Reviewing', 'Approved', 'Rejected', 'Waitlisted')),
    income_amount NUMERIC,
    credit_score INTEGER,
    employment_status VARCHAR(100),
    notes TEXT,
    documents JSONB DEFAULT '[]'::jsonb, -- Array of document URLs
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

ALTER TABLE public.leasing_applications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated full access to leasing_applications" ON public.leasing_applications;
CREATE POLICY "Allow authenticated full access to leasing_applications"
    ON public.leasing_applications FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);


