import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  FileText, 
  Plus, 
  Search, 
  Filter, 
  LayoutGrid, 
  List as ListIcon, 
  MoreHorizontal, 
  Clock, 
  CheckCircle2, 
  AlertCircle, 
  Archive,
  Download,
  Trash2,
  Copy,
  ChevronRight,
  BookOpen,
  Library,
  Scale
} from 'lucide-react';
import { api } from '../services/api';
import { LegalDocument, DocumentTemplate, Property, Tenant } from '../types';
import { useAuth } from '../contexts/AuthContext';
import { useToast } from '../contexts/ToastContext';
import { DocumentEditor } from './DocumentEditor';

export const DocumentManagement: React.FC = () => {
  const { user } = useAuth();
  const { addToast } = useToast();
  const [loading, setLoading] = useState(true);
  const [documents, setDocuments] = useState<LegalDocument[]>([]);
  const [templates, setTemplates] = useState<DocumentTemplate[]>([]);
  const [viewMode, setViewMode] = useState<'grid' | 'list'>('grid');
  const [activeTab, setActiveTab] = useState<'all' | 'templates'>('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('All');
  const [errorDetails, setErrorDetails] = useState<string | null>(null);
  
  // Editor State
  const [isEditorOpen, setIsEditorOpen] = useState(false);
  const [editingDocId, setEditingDocId] = useState<number | undefined>();
  const [selectedTemplate, setSelectedTemplate] = useState<DocumentTemplate | undefined>();

  const loadData = async () => {
    setLoading(true);
    setErrorDetails(null);
    try {
      // Seed templates if needed
      try {
        await api.seedTemplates();
      } catch (seedError) {
        console.warn('Template seeding skipped or failed:', seedError);
        // If seeding fails, we might still want to try loading docs if table exists
      }
      
      const [docsData, templatesData] = await Promise.all([
        api.getLegalDocuments(),
        api.getDocumentTemplates()
      ]);
      setDocuments(docsData);
      setTemplates(templatesData);
    } catch (error) {
      console.error('Failed to load documents:', error);
      const message = error instanceof Error ? error.message : typeof error === 'object' ? JSON.stringify(error) : String(error);
      setErrorDetails(message);
      
      const isMissingTable = message.includes('legal_documents') || message.includes('document_templates') || message.includes('PGRST205');
      
      addToast(
        isMissingTable 
          ? 'Database tables missing. See instructions on screen.'
          : 'Failed to load documents', 
        'error'
      );
    } finally {
      setLoading(false);
    }
  };

  const sqlMigration = `-- Paste this into your Supabase SQL Editor:

CREATE TABLE IF NOT EXISTS public.document_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL,
  name_en text NOT NULL,
  name_so text NOT NULL,
  content_en text NOT NULL,
  content_so text NOT NULL,
  placeholders jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.legal_documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id bigint REFERENCES public.document_templates(id) ON DELETE SET NULL,
  property_id bigint REFERENCES public.properties(id) ON DELETE CASCADE,
  unit_id bigint REFERENCES public.units(id) ON DELETE CASCADE,
  tenant_id bigint REFERENCES public.tenants(id) ON DELETE CASCADE,
  owner_id bigint REFERENCES public.owners(id) ON DELETE CASCADE,
  title text NOT NULL,
  content_en text NOT NULL,
  content_so text NOT NULL,
  placeholders_data jsonb DEFAULT '{}'::jsonb,
  status text DEFAULT 'Draft',
  version integer DEFAULT 1,
  file_url text,
  asset_id uuid REFERENCES public.media_assets(id),
  created_by uuid REFERENCES public.profiles(id),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.document_signatures (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id bigint REFERENCES public.legal_documents(id) ON DELETE CASCADE,
  signer_id uuid REFERENCES public.profiles(id),
  signer_name text,
  signer_role text,
  signature_data text, 
  signed_at timestamptz,
  ip_address text,
  user_agent text
);

CREATE TABLE IF NOT EXISTS public.property_documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id bigint REFERENCES public.properties(id) ON DELETE CASCADE NOT NULL,
  name text NOT NULL,
  url text NOT NULL,
  type text NOT NULL,
  asset_id uuid REFERENCES public.media_assets(id),
  uploaded_at timestamp with time zone DEFAULT now(),
  uploaded_by uuid REFERENCES public.profiles(id)
);

ALTER TABLE public.document_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.legal_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_signatures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.property_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view templates" ON public.document_templates FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can manage templates" ON public.document_templates FOR ALL USING (true);
CREATE POLICY "Authenticated users can view legal docs" ON public.legal_documents FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admins and Managers can manage legal docs" ON public.legal_documents FOR ALL USING (true);
CREATE POLICY "Authenticated users can view signatures" ON public.document_signatures FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can sign docs" ON public.document_signatures FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can read property docs" ON public.property_documents FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admins and Managers can manage property docs" ON public.property_documents FOR ALL USING (true);
`;

  useEffect(() => {
    loadData();
  }, []);

  const filteredDocs = documents.filter(d => {
    const matchesSearch = d.title.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesCategory = selectedCategory === 'All'; // Categorization to be added to model if needed
    return matchesSearch && matchesCategory;
  });

  const categories = ['All', 'Lease', 'Notice', 'Financial', 'Property Management'];

  const handleCreateFromTemplate = (template: DocumentTemplate) => {
    setSelectedTemplate(template);
    setEditingDocId(undefined);
    setIsEditorOpen(true);
  };

  const handleEditDocument = (id: number) => {
    setEditingDocId(id);
    setSelectedTemplate(undefined);
    setIsEditorOpen(true);
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Signed': return 'text-emerald-600 bg-emerald-50 dark:bg-emerald-900/20';
      case 'Pending': return 'text-amber-600 bg-amber-50 dark:bg-amber-900/20';
      case 'Draft': return 'text-zinc-500 bg-zinc-50 dark:bg-zinc-800';
      default: return 'text-zinc-400 bg-zinc-50 dark:bg-zinc-800';
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="w-10 h-10 border-4 border-violet-600 border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="p-8 space-y-12 max-w-[1600px] mx-auto">
      {/* Hero Section */}
      <div className="relative group">
        <div className="vintsy-card p-12 overflow-hidden bg-zinc-900 dark:bg-white text-white dark:text-zinc-900 transition-all duration-700">
          <div className="relative z-10 flex flex-col md:flex-row justify-between items-end md:items-center gap-8">
            <div className="space-y-4">
              <div className="flex items-center gap-3">
                 <div className="w-10 h-10 rounded-2xl bg-white/10 dark:bg-zinc-900/5 flex items-center justify-center">
                    <Scale size={20} className="text-violet-400" />
                 </div>
                 <span className="text-[10px] font-bold uppercase tracking-[0.3em] opacity-60">Legal Excellence • Somalia</span>
              </div>
              <h1 className="text-4xl md:text-5xl font-black tracking-tight leading-none">
                 Lease & Documents <br />
                 <span className="text-violet-400">Workflow Hub</span>
              </h1>
              <p className="text-zinc-400 text-sm max-w-xl font-medium tracking-wide">
                 Professional, bilingual documentation management system specifically designed for Somalia's property jurisdiction and legal standards.
              </p>
            </div>
            
            <button 
              onClick={() => setActiveTab('templates')}
              className="px-8 py-5 bg-violet-600 text-white rounded-[2rem] text-xs font-bold uppercase tracking-widest hover:bg-violet-500 transition-all shadow-2xl shadow-violet-600/30 flex items-center gap-3 group/btn"
            >
              <Plus size={18} className="group-hover/btn:rotate-90 transition-transform duration-500" />
              Generate New Document
              <ChevronRight size={16} />
            </button>
          </div>

          <div className="absolute right-0 bottom-0 opacity-10 pointer-events-none">
             <FileText size={400} strokeWidth={0.5} />
          </div>
        </div>
      </div>

      {/* Main Tabs & Filters */}
      <div className="space-y-8">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
           <div className="flex bg-white dark:bg-zinc-900 p-1.5 rounded-2xl border border-zinc-100 dark:border-zinc-800 shadow-sm">
             <button 
               onClick={() => setActiveTab('all')}
               className={`flex items-center gap-3 px-8 py-3 rounded-xl text-[10px] font-bold uppercase tracking-widest transition-all ${
                 activeTab === 'all' ? 'bg-zinc-900 dark:bg-white text-white dark:text-zinc-900 shadow-xl' : 'text-zinc-500 hover:text-zinc-900 dark:hover:text-white'
               }`}
             >
               <FileText size={16} />
               Records Hub
             </button>
             <button 
               onClick={() => setActiveTab('templates')}
               className={`flex items-center gap-3 px-8 py-3 rounded-xl text-[10px] font-bold uppercase tracking-widest transition-all ${
                 activeTab === 'templates' ? 'bg-zinc-900 dark:bg-white text-white dark:text-zinc-900 shadow-xl' : 'text-zinc-500 hover:text-zinc-900 dark:hover:text-white'
               }`}
             >
               <Library size={16} />
               Template Library
             </button>
           </div>

           <div className="flex items-center gap-4 w-full md:w-auto">
             <div className="relative flex-1 md:w-80 group">
               <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-400 transition-colors group-focus-within:text-violet-600" size={14} />
               <input 
                 type="text" 
                 placeholder="Search documents by title or tenant..."
                 value={searchQuery}
                 onChange={(e) => setSearchQuery(e.target.value)}
                 className="vintsy-input w-full pl-12 pr-4 py-3"
               />
             </div>
             <div className="flex bg-white dark:bg-zinc-900 p-1.5 rounded-2xl border border-zinc-100 dark:border-zinc-800 shadow-sm">
               <button 
                 onClick={() => setViewMode('grid')}
                 className={`p-2 rounded-lg transition-all ${viewMode === 'grid' ? 'bg-zinc-100 dark:bg-zinc-800 text-zinc-900 dark:text-white' : 'text-zinc-400'}`}
               >
                 <LayoutGrid size={16} />
               </button>
               <button 
                 onClick={() => setViewMode('list')}
                 className={`p-2 rounded-lg transition-all ${viewMode === 'list' ? 'bg-zinc-100 dark:bg-zinc-800 text-zinc-900 dark:text-white' : 'text-zinc-400'}`}
               >
                 <ListIcon size={16} />
               </button>
             </div>
           </div>
        </div>

        {/* Category Filters */}
        <div className="flex gap-2 overflow-x-auto pb-4 scrollbar-hide">
          {categories.map((cat) => (
            <button 
              key={cat}
              onClick={() => setSelectedCategory(cat)}
              className={`px-6 py-2.5 rounded-full text-[10px] font-bold uppercase tracking-widest border transition-all shrink-0 ${
                selectedCategory === cat 
                  ? 'bg-violet-600 border-violet-600 text-white shadow-lg shadow-violet-600/20' 
                  : 'bg-white dark:bg-zinc-900 border-zinc-100 dark:border-zinc-800 text-zinc-500 hover:border-violet-600 hover:text-violet-600'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>

        {activeTab === 'all' ? (
          <>
            {errorDetails ? (
              <div className="vintsy-card p-12 text-center space-y-6 border-red-100 dark:border-red-900/30">
                 <div className="w-16 h-16 bg-red-50 dark:bg-red-900/20 rounded-3xl flex items-center justify-center text-red-500 mx-auto">
                    <AlertCircle size={32} />
                 </div>
                 <div className="max-w-2xl mx-auto text-left">
                    <h3 className="text-lg font-bold text-zinc-900 dark:text-white mb-2 tracking-tight text-center">Legal Database Synchronization Error</h3>
                    <p className="text-zinc-400 text-sm mb-6 text-center">The following tables are missing from your database schema. Please paste the SQL below into your Supabase SQL Editor.</p>
                    
                    <div className="relative group">
                      <pre className="text-zinc-500 text-[10px] font-mono bg-zinc-50 dark:bg-zinc-800/50 p-6 rounded-xl border border-zinc-100 dark:border-zinc-800 overflow-x-auto max-h-60 scrollbar-hide">
                        {sqlMigration}
                      </pre>
                      <button 
                        onClick={() => {
                          navigator.clipboard.writeText(sqlMigration);
                          addToast('SQL copied to clipboard', 'info');
                        }}
                        className="absolute top-4 right-4 p-2 bg-white dark:bg-zinc-700 shadow-sm rounded-lg opacity-0 group-hover:opacity-100 transition-opacity"
                      >
                        <Copy size={14} className="text-zinc-500" />
                      </button>
                    </div>

                    <p className="text-zinc-500 text-[10px] mt-6 italic font-medium">Error Details: {errorDetails}</p>
                 </div>
                 <div className="flex justify-center gap-4">
                   <button 
                    onClick={loadData}
                    className="px-10 py-4 bg-zinc-900 dark:bg-white text-white dark:text-zinc-900 rounded-2xl text-[10px] font-bold uppercase tracking-widest hover:opacity-90 transition-all shadow-xl"
                   >
                     Retry Connection
                   </button>
                 </div>
              </div>
            ) : filteredDocs.length === 0 ? (
              <div className="vintsy-card p-24 text-center space-y-6">
                 <div className="w-20 h-20 bg-zinc-50 dark:bg-zinc-800 rounded-3xl flex items-center justify-center text-zinc-300 mx-auto">
                    <FileText size={40} />
                 </div>
                 <div>
                    <h3 className="text-lg font-bold text-zinc-900 dark:text-white mb-2 tracking-tight">No Documents Found</h3>
                    <p className="text-zinc-400 text-sm max-w-xs mx-auto">Try adjusting your search or generate a new document from the templates library.</p>
                 </div>
                 <button 
                  onClick={() => setActiveTab('templates')}
                  className="text-[10px] font-bold text-violet-600 uppercase tracking-widest hover:underline px-6 py-3"
                 >
                   Browse Template Library
                 </button>
              </div>
            ) : viewMode === 'grid' ? (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
                {filteredDocs.map((doc) => (
                  <motion.div 
                    layout
                    key={doc.id} 
                    className="vintsy-card group h-full flex flex-col hover:border-violet-200 dark:hover:border-violet-800"
                  >
                    <div className="p-8 space-y-6 flex-1">
                       <div className="flex items-start justify-between">
                         <div className={`p-4 rounded-2xl ${getStatusColor(doc.status)}`}>
                           <FileText size={24} />
                         </div>
                         <div className="flex flex-col items-end gap-2">
                            <span className={`px-2.5 py-1 rounded-full text-[8px] font-bold uppercase tracking-widest ${getStatusColor(doc.status)}`}>
                              {doc.status}
                            </span>
                            <span className="text-[8px] text-zinc-400 font-bold uppercase tracking-widest italic">v{doc.version}.0</span>
                         </div>
                       </div>
                       
                       <div className="space-y-2">
                         <h3 className="text-sm font-bold text-zinc-900 dark:text-white group-hover:text-violet-600 transition-colors line-clamp-2">
                           {doc.title}
                         </h3>
                         <div className="flex items-center gap-2 text-zinc-400">
                           <Clock size={12} />
                           <span className="text-[10px] font-medium tracking-wide">Updated {new Date(doc.updated_at).toLocaleDateString()}</span>
                         </div>
                       </div>

                       <div className="pt-6 border-t border-zinc-50 dark:border-zinc-800 flex flex-wrap gap-4">
                          <div className="flex-1 space-y-1">
                             <p className="text-[8px] font-bold text-zinc-400 uppercase tracking-widest">Signatures</p>
                             <div className="flex -space-x-2">
                               {[1, 2].map(i => (
                                 <div key={i} className={`w-6 h-6 rounded-full border-2 border-white dark:border-zinc-900 flex items-center justify-center ${
                                   doc.signatures && doc.signatures.length >= i ? 'bg-emerald-100 text-emerald-600' : 'bg-zinc-100 dark:bg-zinc-800 text-zinc-400'
                                 }`}>
                                   <CheckCircle2 size={10} />
                                 </div>
                               ))}
                             </div>
                          </div>
                          {doc.placeholders_data && (
                            <div className="flex-1 text-right space-y-1">
                               <p className="text-[8px] font-bold text-zinc-400 uppercase tracking-widest">Type</p>
                               <p className="text-[10px] font-bold text-zinc-900 dark:text-white truncate">Official</p>
                            </div>
                          )}
                       </div>
                    </div>
                    
                    <div className="px-8 py-6 bg-zinc-50 dark:bg-zinc-900/50 flex items-center justify-between border-t border-zinc-100 dark:border-zinc-800">
                       <button 
                        onClick={() => handleEditDocument(doc.id)}
                        className="text-[10px] font-bold text-violet-600 uppercase tracking-widest hover:underline"
                       >
                         Manage Doc
                       </button>
                       <div className="flex items-center gap-3">
                         <button className="p-2 text-zinc-400 hover:text-zinc-600 transition-colors"><Download size={14} /></button>
                         <button className="p-2 text-zinc-400 hover:text-red-500 transition-colors"><Trash2 size={14} /></button>
                       </div>
                    </div>
                  </motion.div>
                ))}
              </div>
            ) : (
              <div className="vintsy-card overflow-hidden">
                <table className="w-full text-left">
                  <thead className="bg-zinc-50 dark:bg-zinc-900/50 border-b border-zinc-100 dark:border-zinc-800">
                    <tr>
                      <th className="px-8 py-5 text-[10px] font-bold text-zinc-400 uppercase tracking-widest">Document Title</th>
                      <th className="px-8 py-5 text-[10px] font-bold text-zinc-400 uppercase tracking-widest">Status</th>
                      <th className="px-8 py-5 text-[10px] font-bold text-zinc-400 uppercase tracking-widest">Signatures</th>
                      <th className="px-8 py-5 text-[10px] font-bold text-zinc-400 uppercase tracking-widest">Last Updated</th>
                      <th className="px-8 py-5 text-right"></th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-zinc-100 dark:divide-zinc-800">
                    {filteredDocs.map((doc) => (
                      <tr key={doc.id} className="hover:bg-zinc-50/50 dark:hover:bg-zinc-900/30">
                        <td className="px-8 py-6">
                           <div className="flex items-center gap-4">
                             <div className={`p-2.5 rounded-xl ${getStatusColor(doc.status)}`}>
                               <FileText size={18} />
                             </div>
                             <div>
                               <p className="text-sm font-bold text-zinc-900 dark:text-white">{doc.title}</p>
                               <p className="text-[10px] text-zinc-400 font-bold uppercase tracking-widest">v{doc.version}.0</p>
                             </div>
                           </div>
                        </td>
                        <td className="px-8 py-6">
                          <span className={`px-2.5 py-1 rounded-full text-[8px] font-bold uppercase tracking-widest ${getStatusColor(doc.status)}`}>
                            {doc.status}
                          </span>
                        </td>
                        <td className="px-8 py-6">
                           <div className="flex -space-x-1.5">
                              {[1, 2].map(i => (
                                <div key={i} className={`w-5 h-5 rounded-full border-2 border-white dark:border-zinc-900 flex items-center justify-center ${
                                  doc.signatures && doc.signatures.length >= i ? 'bg-emerald-100 text-emerald-600' : 'bg-zinc-100 dark:bg-zinc-800 text-zinc-400'
                                }`}>
                                  <CheckCircle2 size={8} />
                                </div>
                              ))}
                           </div>
                        </td>
                        <td className="px-8 py-6 text-[10px] font-medium text-zinc-500">
                          {new Date(doc.updated_at).toLocaleDateString()}
                        </td>
                        <td className="px-8 py-6 text-right">
                          <button 
                            onClick={() => handleEditDocument(doc.id)}
                            className="p-2 text-zinc-400 hover:text-violet-600 transition-colors"
                          >
                            <MoreHorizontal size={18} />
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
            {templates.filter(t => selectedCategory === 'All' || t.category === selectedCategory).map((template) => (
              <motion.div 
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                key={template.id} 
                className="vintsy-card group flex flex-col hover:border-emerald-200 dark:hover:border-emerald-800"
              >
                <div className="p-8 space-y-6 flex-1">
                   <div className="flex items-start justify-between">
                     <div className="p-4 rounded-2xl bg-emerald-50 dark:bg-emerald-900/20 text-emerald-600">
                       <LayoutGrid size={24} />
                     </div>
                     <span className="px-2.5 py-1 rounded-full text-[8px] font-bold bg-zinc-100 dark:bg-zinc-800 text-zinc-500 uppercase tracking-widest">
                       Bilingual
                     </span>
                   </div>
                   
                   <div className="space-y-4">
                     <div>
                       <h3 className="text-sm font-bold text-zinc-900 dark:text-white line-clamp-1">{template.name_en}</h3>
                       <p className="text-[10px] font-bold text-emerald-600 uppercase tracking-widest mt-1">{template.name_so}</p>
                     </div>
                     <p className="text-xs text-zinc-500 line-clamp-2 leading-relaxed">
                       Standard Somalia legal template with support for {(Array.isArray(template.placeholders) ? template.placeholders : []).length} dynamic fields.
                     </p>
                   </div>
                </div>
                
                <div className="px-8 py-6 bg-zinc-50 dark:bg-zinc-900/50 flex items-center justify-between border-t border-zinc-100 dark:border-zinc-800">
                   <button 
                    onClick={() => handleCreateFromTemplate(template)}
                    className="flex-1 py-3 bg-emerald-600 text-white rounded-xl text-[10px] font-bold uppercase tracking-widest hover:bg-emerald-700 transition-all flex items-center justify-center gap-2 group/btn"
                   >
                     Use Template
                     <ChevronRight size={14} className="group-hover/btn:translate-x-1 transition-transform" />
                   </button>
                </div>
              </motion.div>
            ))}
          </div>
        )}
      </div>

      <AnimatePresence>
        {isEditorOpen && (
          <DocumentEditor 
            documentId={editingDocId}
            template={selectedTemplate}
            onClose={() => setIsEditorOpen(false)}
            onSave={() => {
              setIsEditorOpen(false);
              loadData();
            }}
          />
        )}
      </AnimatePresence>
    </div>
  );
};
